[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NETLIFY_NEXT_PLUGIN_FORCE_BUILD = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@clerk/nextjs"]
  included_files = ["**/*.node"]

# Specific rule for image files - add this before the catch-all rule
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[plugins]]
  package = "@netlify/plugin-nextjs"
  # No additional inputs needed for the latest version

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"
  publish = ".next"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.clerk.accounts.dev; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.clerk.accounts.dev;"
